### ISSUE TITLE
Calendar ID's as Main Account Email

### ISSUE THREAD

**Issue by mikes-bowden** [karbassi/sync-multiple-google-calendars#29]
I'm having an issue with appointments not pulling from calendars that my primary account has access to, but they are the primary calendar for the other account. That's confusing, so let me break it down.

Primary Account = Where the script is running and the one with all the access.
Account 1 = The primary calendar is being shared for the account.
Account 2 = The primary calendar is being shared for the account.

For Accounts 1 and 2, the Calendar ID is the account's email, not a generated calendar id email. I have full read/write access to all of them, but I can't pull anything from them.

Any ideas?

Thanks, and awesome script!

**Comment by karbassi** [comment]
When you run it, what does the output say?

**Comment by mikes-bowden** [comment]
> When you run it, what does the output say?

No errors. Here's a new run log.

```
Execution log
7:47:33 PM	Notice	Execution started
7:47:40 PM	Info	7 deleted events between Tue Feb 01 2000 00:00:00 GMT-0600 (Central Standard Time) and Wed Mar 15 2023 00:00:00 GMT-0500 (Central Daylight Time).
7:47:42 PM	Info	7 events created between Sun Feb 05 2023 00:00:00 GMT-0600 (Central Standard Time) and Wed Mar 15 2023 00:00:00 GMT-0500 (Central Daylight Time).
7:47:43 PM	Notice	Execution completed
```

**Comment by mikes-bowden** [comment]
I don't know what happened, but it started working. It would have to be something on Google's end because I haven't changed any permissions or the code set to run.

Needless to say, this can be closed. :)

Thanks for the help.
